### PR TITLE
Objects - 08 Rectangle problem

### PR DESCRIPTION
**Pull request by fabriciovd**
This is a test directly from WebStorm. I'm trying to use direct access addons from the IDE.

### CODE REVIEW

**Review by crystal-wolfer — APPROVED** [review]
доста чист и четим код :)

**Comment by georgi-georgiev95** [comment]
Test successful.

**Review by georgi-georgiev95 — APPROVED** [review]
Test successful.

**Comment by crystal-wolfer** [comment]
Merged & Closed

**Pull request merged**
